export enum ProjectRoutes {
  Home = '/',
  Portfolio = '/portfolio',
  Landing = '/landing',
  Main = '/main',
  About = '/about',
  CV = '/cv',
  Projects = '/projects',
  ProjectsFilter = '/projects/:filter',
  Project = '/project/:id',
  AnyProject = '/project',
  Missing = '*',
  Colors = '/colors',
  CreateMotivationLetter = '/create-motivation-letter',
}
