export enum Keywords {
  ThreeDPrinting = '3d-printing',
  Product = 'product',
  Development = 'development',
  Ecology = 'ecology',
  Frontend = 'frontend',
  Shaders = 'shaders',
  Geometry = 'geometry',
  Knitting = 'knitting',
  Patterns = 'patterns',
  DigitalFabrication = 'dfab',
  Workshop = 'workshop',
  Timber = 'timber',
  Static = 'static',
  AI = 'ai',
}
