export enum Technologies {
  FDM = 'FDM',
  BinderJet = 'Binder Jet',
  ClayPrinting = 'Clay Printing',
  VacuumForming = 'Vacuum Forming',
  Java = 'Java',
  Processing = 'Processing',
  JavaScript = 'Java Script',
  GLSL = 'GLSL',
  BabylonJS = 'Babylon JS',
  ThreeJS = 'Three JS',
  TypeScript = 'Type Script',
  Python = 'Python',
  Numpy = 'numpy',
  Paperspace = 'Paperspace',
  OpenCV = 'Open CV',
  CSharp = 'C Sharp',
  Rhino = 'Rhino',
  Grasshopper = 'Grasshopper',
  React = 'React',
  ROS = 'ROS',
  GRBL = 'GRBL',
  GCode = 'GCode',
}
